# Generated by Django 4.0.3 on 2022-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcategory',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
