# Generated by Django 4.0.3 on 2022-03-24 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumcategory_title_alter_forumthread_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='category',
        ),
        migrations.AddField(
            model_name='forumpost',
            name='thread',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forum.forumthread'),
            preserve_default=False,
        ),
    ]
