# Generated by Django 4.0.3 on 2022-03-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumthread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, null=True),
        ),
    ]
