# Generated by Django 4.0.3 on 2022-04-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_profile_alter_forumpost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='date_edited',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
