# Generated by Django 4.0.3 on 2022-04-09 10:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_alter_forumpost_options_forumpost_is_reply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
